# You can configure every entityID/name (without spaces) or a default!
cantAfford: "&e[SilkSpawnersEco] &4Sorry, but you can't change the mob of this spawner, because you have not enough money!"
afford: "&e[SilkSpawnersEco] &2This action costs &e%money%"
sameMob: "&e[SilkSpawnersEco] &2This action was free, because it's the same mob!"
confirmationPending: "&e[SilkSpawnersEco] Remember that changing the spawner costs money, if you want to continue, do the action again!"
chargeSameMob: false
chargeXP: false
chargeMultipleAmounts: false
confirmation:
  enabled: false
  delay: 30
default: 10.5
pig: 7.25
cow: 0.00
