# You can configure every entityID/name (without spaces) or a default!
chargeSameMob: false
chargeXP: false
chargeBoth: false
chargeMultipleAmounts: false
confirmation:
  enabled: false
  delay: 30
default:
  money: 10.5
  xp: 100
pig:
  money: 7.25
  xp: 200
cow:
  money: 0.0
  xp: 20
