name: SilkSpawnersEcoAddon
author: xGhOsTkiLLeRx
main: de.dustplanet.silkspawnersecoaddon.SilkSpawnersEcoAddon
version: ${project.version}-b${BUILD_NUMBER}
url: http://dev.bukkit.org/server-mods/silkspawnersecoaddon/
description: Use Vault as an economy based hook to charge changing of spawners
permissions:
    silkspawners.free:
        description: Allows you to bypass the economy check
        default: op
depend: [SilkSpawners]
softdepend: [Vault]