name: SilkSpawnersEcoAddon
author: xGhOsTkiLLeRx
main: de.dustplanet.silkspawnersecoaddon.SilkSpawnersEcoAddon
version: ${project.version}${build.number}
website: http://dev.bukkit.org/server-mods/silkspawnersecoaddon/
description: Use Vault as an economy based hook to charge actions regarding spawner interaction
api-version: 1.13
commands:
    silkspawnerseco:
        aliases: [silkspawnersecoaddon, silkspawnerecoaddon, silkspawnereco]
        description: Reloads config file of SilkSpawnersEcoAddon
        usage: /<command> reload
permissions:
    silkspawners.free:
        description: Allows you to bypass the economy check
        default: op
depend: [SilkSpawners]
softdepend: [Vault]
