_job_base: &job_base
  working_directory: ~/silk-spawners-eco-addon
  steps:
    - checkout
    - run: java -version
    - run: mvn -version
    - restore_cache:
        key: silk-spawners-eco-addon-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: silk-spawners-eco-addon-{{ checksum "pom.xml" }}
    - run: mvn clean package -Pmetrics

version: 2
jobs:
  jdk8:
    <<: *job_base
    docker:
      - image: maven:3-jdk-8-slim
  jdk10:
    <<: *job_base
    docker:
      - image: maven:3-jdk-10-slim
workflows:
  version: 2
  all_jdks:
    jobs:
      - jdk8
      - jdk10
